### ISSUE TITLE
Bug in reporter (utils.js:55)

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/mukla#14]
maybe when stack is too short

```
/home/charlike/apps/native-or-another/node_modules/mukla/utils.js:55
    ? lines[1].trim().slice(3)
               ^
TypeError: Cannot call method 'trim' of undefined
    at Function.diagnostic [as diag] (/home/charlike/apps/native-or-another/node_modules/mukla/utils.js:55:16)
    at fail (/home/charlike/apps/native-or-another/node_modules/mukla/index.js:108:25)
    at /home/charlike/apps/native-or-another/node_modules/mukla/index.js:58:46
    at cb (/home/charlike/apps/native-or-another/node_modules/always-done/index.js:64:9)
    at /home/charlike/apps/native-or-another/node_modules/dezalgo/dezalgo.js:17:12
    at RawTask.call (/home/charlike/apps/native-or-another/node_modules/asap/asap.js:40:19)
    at flush (/home/charlike/apps/native-or-another/node_modules/asap/raw.js:50:29)
    at process._tickCallback (node.js:458:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
```

this fix and using `redolent` instead of `always-done` maybe will be the last version before v1

edit: it seem it fails when `Missing exception` error is thrown

```
  ---
  name: AssertionError
  message: Missing expected exception (Error)..
  expected: { [Function: Error]
  captureStackTrace: [Function: captureStackTrace],
  stackTraceLimit: 10 }
  ...
```

**Comment by tunnckoCore** [comment]
https://github.com/tunnckoCore/mukla/commit/39929919e845c58f14ec7108779618996ccdb6e6
