### ISSUE TITLE
bug when Error don't have stack

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/mukla#9]
```
/home/charlike/dev/node_modules/stack-utils/index.js:30
        stack = stack.split('\n');
                     ^

TypeError: Cannot read property 'split' of undefined
    at StackUtils.clean (/home/charlike/dev/node_modules/stack-utils/index.js:30:16)
    at fail (/home/charlike/dev/node_modules/mukla/index.js:116:28)
    at /home/charlike/dev/node_modules/mukla/index.js:68:46
    at f (/home/charlike/dev/node_modules/once/once.js:25:25)
```

I strongly believe that this should be handled in SatckUtils's `.clean` (or at least throw with good msg), but as usual, most of the stuff around Sindre & co sucks and this can be done here.

**Comment by tunnckoCore** [comment]
https://github.com/tunnckoCore/mukla/commit/3b7d301383fc93a018de57bd0e1a6143d2d13b07
